language: php

php:
  # - 5.4
  # - 5.5
  - 5.6

env:
  # - LIBSODIUM_VERSION=master ZEROMQ_VERSION=master CZMQ_VERSION=master ZYRE_VERSION=master MAJORDOMO_VERSION=master FILEMQ_VERSION=master MALAMUTE_VERSION=master PHPCPP_VERSION=master
  # - LIBSODIUM_VERSION=1.0.3 ZEROMQ_VERSION=6e064f9f757af466b007b59c4ea4e19de0568548 CZMQ_VERSION=v3.0.2 ZYRE_VERSION=v1.1.0 MAJORDOMO_VERSION=d24642793e62a2b2f77419481f9a2020364fd1b1 FILEMQ_VERSION=acf6c0e003fee938994ad803aa7b78245dca57ba MALAMUTE_VERSION=814629dd605838323e2321a69325ba91f58eff46 PHPCPP_VERSION=aec191bc6cbb83884466800a750ecad0b37e254f
  - LIBSODIUM_VERSION=1.0.3 ZEROMQ_VERSION=v4.1.3 CZMQ_VERSION=v3.0.2 ZYRE_VERSION=v1.1.0 MAJORDOMO_VERSION=d24642793e62a2b2f77419481f9a2020364fd1b1 FILEMQ_VERSION=acf6c0e003fee938994ad803aa7b78245dca57ba MALAMUTE_VERSION=master PHPCPP_VERSION=aec191bc6cbb83884466800a750ecad0b37e254f

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update -qq
  - composer self-update

install:
  - sudo apt-get install -qq git g++-4.8 uuid-dev build-essential autoconf php5-dev pkg-config
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script: ./travis/build.sh