language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - composer self-update

install:
  - sudo apt-get install -qq g++-4.8 uuid-dev build-essential autoconf php5-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
  - git clone git://github.com/CopernicaMarketingSoftware/PHP-CPP.git && ( cd PHP-CPP; make -j4 && sudo make install && sudo ldconfig && cd ..)
