language: php

php:
#  - 5.4
#  - 5.5
  - 5.6

env:
  - ZMQ_REPO=libzmq LIBSODIUM_REPO=libsodium CZMQ_REPO=czmq ZYRE_REPO=zyre MALAMUTE_REPO=malamute

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - composer self-update

install:
#  - sudo apt-get install -qq --force-yes -y g++-4.8 uuid-dev build-essential autoconf php5-dev valgrind gdb
  - sudo apt-get install -qq g++-4.8 uuid-dev build-essential autoconf
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script: ./build.sh

notifications:
  email:
    recipients: goddanao@gmail.com
    on_success: change
    on_failure: always