language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - ZEROMQ_VERSION=master LIBSODIUM_VERSION=master CZMQ_VERSION=master ZYRE_VERSION=master MAJORDOMO_VERSION=master MALAMUTE_VERSION=master FILEMQ_VERSION=master PHPCPP_VERSION=master
  # - ZEROMQ_VERSION=v4.0.7 LIBSODIUM_VERSION=1.0.3 CZMQ_VERSION=v3.0.0 ZYRE_VERSION=master MAJORDOMO_VERSION=master MALAMUTE_VERSION=master FILEMQ_VERSION=master PHPCPP_VERSION=master

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update -qq
  - composer self-update

install:
  - sudo apt-get install -qq git g++-4.8 uuid-dev build-essential autoconf php5-dev pkg-config
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script: ./travis/build.sh