language: php

php:
  - 5.4
  - 5.5
  - 5.6

os:
  - linux

env:
  - LIBSODIUM_VERSION=master ZEROMQ_VERSION=master CZMQ_VERSION=master ZYRE_VERSION=master MAJORDOMO_VERSION=master FILEMQ_VERSION=master MALAMUTE_VERSION=master PHPCPP_VERSION=master
  - LIBSODIUM_VERSION=1.0.3 ZEROMQ_VERSION=e56b486735908ac5b1fd740dc17a832317f9cade CZMQ_VERSION=v3.0.2 ZYRE_VERSION=v1.1.0 MAJORDOMO_VERSION=5bbd130e9dbabe2a6757698fa87e08c71383ec15 FILEMQ_VERSION=acf6c0e003fee938994ad803aa7b78245dca57ba MALAMUTE_VERSION=814629dd605838323e2321a69325ba91f58eff46 PHPCPP_VERSION=570590058d16274005a4994fd8f1046d0eaf7f74
  - LIBSODIUM_VERSION=1.0.3 ZEROMQ_VERSION=v4.1.3 CZMQ_VERSION=v3.0.2 ZYRE_VERSION=v1.1.0 MAJORDOMO_VERSION=5bbd130e9dbabe2a6757698fa87e08c71383ec15 FILEMQ_VERSION=acf6c0e003fee938994ad803aa7b78245dca57ba MALAMUTE_VERSION=814629dd605838323e2321a69325ba91f58eff46 PHPCPP_VERSION=570590058d16274005a4994fd8f1046d0eaf7f74

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update -qq
  - composer self-update
  - sudo apt-get install -qq git g++-4.8 uuid-dev build-essential autoconf php5-dev pkg-config
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

install:
  - ./install/install.sh
  - composer install --no-dev -n

script:
  - $(which phpunit) -dzend.enable_gc=0