language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - ZEROMQ_VERSION=master ZEROMQ_HASH="" LIBSODIUM_VERSION=master LIBSODIUM_HASH="" CZMQ_VERSION=master CZMQ_HASH=8bbab31200ba629cafacb9027d1b5f2b01c383f0 ZYRE_VERSION=master ZYRE_HASH=3691e3f51c33ed5d7b9d8c9f01f1511b5205f805 MAJORDOMO_VERSION=master MAJORDOMO_HASH="" MALAMUTE_VERSION=master MALAMUTE_HASH="" FILEMQ_VERSION=master FILEMQ_HASH="" PHPCPP_VERSION=master PHPCPP_HASH=""
  - ZEROMQ_VERSION=v4.0.7 ZEROMQ_HASH="" LIBSODIUM_VERSION=1.0.3 LIBSODIUM_HASH="" CZMQ_VERSION=v3.0.2 CZMQ_HASH="" ZYRE_VERSION=v1.1.0 ZYRE_HASH="" MAJORDOMO_VERSION=master MAJORDOMO_HASH="" MALAMUTE_VERSION=master MALAMUTE_HASH="" FILEMQ_VERSION=master FILEMQ_HASH="" PHPCPP_VERSION=master PHPCPP_HASH=""

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update -qq
  - composer self-update

install:
  - sudo apt-get install -qq git g++-4.8 uuid-dev build-essential autoconf php5-dev pkg-config
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script: ./travis/build.sh