
language: cpp

compiler:
  - gcc

env:
  - ZMQ_REPO=libzmq    WITH_LIBSODIUM=1 CZMQ_REPO=czmq ZYRE_REPO=zyre MALAMUTE_REPO=malamute-core
# - ZMQ_REPO=zeromq4-x WITH_LIBSODIUM=1 CZMQ_REPO=czmq ZYRE_REPO=zyre MALAMUTE_REPO=malamute-core

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

# need to install the dependencies
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install uuid-dev php5-dev

script: ./.travis/ci_build.sh

after_success:
  - echo "extension=czmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

notifications:
  email:
    recipients: goddanao@gmail.com
    on_success: change
    on_failure: always