
language: cpp

compiler:
  - gcc

env:
- ZMQ_REPO=libzmq    WITH_LIBSODIUM=1 CZMQ_REPO=czmq ZYRE_REPO=zyre MALAMUTE_REPO=malamute-core
# - ZMQ_REPO=zeromq4-x WITH_LIBSODIUM=1 CZMQ_REPO=czmq ZYRE_REPO=zyre MALAMUTE_REPO=malamute-core

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
  # - if [ "$CXX" == "g++" ]; then export CXXFLAGS="-w -c -O2 -g -std=c++11 -fpic -o"; fi

# need to install the dependencies
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install uuid-dev php5-dev

script: ./.travis/ci_build.sh

notifications:
  email:
    recipients: goddanao@gmail.com
    on_success: change
    on_failure: always