language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - ZSYS_INTERFACE=venet0 ZMQ_REPO=libzmq LIBSODIUM_REPO=libsodium CZMQ_REPO=czmq ZYRE_REPO=zyre MAJORDOMO_REPO=majordomo MALAMUTE_REPO=malamute FILEMQ_REPO=filemq
  - ZSYS_INTERFACE=venet0 ZMQ_REPO=zeromq4-x LIBSODIUM_REPO=libsodium CZMQ_REPO=czmq CZMQ_BRANCH="-b 'v3.0.0'" ZYRE_REPO=zyre MAJORDOMO_REPO=majordomo MALAMUTE_REPO=malamute FILEMQ_REPO=filemq
  - ZSYS_INTERFACE=venet0 ZMQ_REPO=zeromq3-x LIBSODIUM_REPO=libsodium CZMQ_REPO=czmq CZMQ_BRANCH="-b 'v2.2.0'" ZYRE_REPO=zyre MAJORDOMO_REPO=majordomo MALAMUTE_REPO=malamute FILEMQ_REPO=filemq

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update -qq
  - composer self-update

install:
  - sudo apt-get install -qq git g++-4.8 uuid-dev build-essential autoconf php5-dev valgrind gdb
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script: ./build.sh